version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "docker"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgres/data
volumes:
  data:
